# Generated by Django 4.1.9 on 2024-01-18 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=60)),
                ('password', models.CharField(max_length=16)),
                ('username', models.CharField(max_length=20, unique=True)),
                ('mobileNumber', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MovieDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.IntegerField()),
                ('language', models.CharField(max_length=50)),
                ('genre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MovieTiming',
            fields=[
                ('id_timing', models.AutoField(primary_key=True, serialize=False)),
                ('movie_id', models.IntegerField()),
                ('theatre_id', models.IntegerField()),
                ('timing', models.DateTimeField(auto_now_add=True)),
                ('bookedSeats', models.CharField(max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('seat_id', models.AutoField(primary_key=True, serialize=False)),
                ('seat_no', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Theatre',
            fields=[
                ('theatre_id', models.AutoField(primary_key=True, serialize=False)),
                ('theatre_name', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movie_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=300)),
                ('rating', models.FloatField()),
                ('theatres', models.ManyToManyField(related_name='movies', to='movie_app.theatre')),
            ],
        ),
    ]
